### PR TITLE
Added tests, comments, Integer .median() and .range()

### PR DESCRIPTION
**Pull request by goreRatzete**
Hey there.

I just had a look at the code, tried to understand it and started adding some tests / comments to make things more clear (to me at least). 

I also started work on the IntegerStatistics. 

I added kluent for testing and updated the gradle wrapper (now with incremental build).

If you have any issues with my style of implementation, just tell me.

### CODE REVIEW

**Comment by thomasnield** [comment]
Excellent thank you.

**Comment by thomasnield** [comment]
After merging, I realized I missed the `range()`. I don't know if I agree with calling it that or even including it. Kind of simple to achieve using just `min()` and `max()`. I'll think about it.

**Comment by thomasnield** [comment]
Technically from a statistics standpoint, it is correct. It might be confusing from a programming standpoint though...

**Comment by goreRatzete** [comment]
yeah i agree it's not very relevant. i just included it to get things started. ill remove it later.

**Pull request merged**
